name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
      with:
          dotnet-version: '8.x'
    - run: dotnet build --configuration Release
    - run: dotnet test
